<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.30.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Yanwai.Ocr\Yanwai.Ocr.csproj" />
    <ProjectReference Include="..\Yanwai.Ocr.Windows\Yanwai.Ocr.Windows.csproj" />
  </ItemGroup>
</Project>
